config/routes.rb
SampleApp::Application.routes.draw do
  resources :users

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/orgbank', to: 'static_pages#orgbank'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def orgbank
  end	

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

   def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Responsabilidad Social Uniandina"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a>Página de Responsabilidad Social</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://uniandes.edu.co">News</a></li>
    </ul>
  </nav>
</footer>  

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Ayudandes", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Banco de Organizaciones",    orgbank_path %></li>
          <li><%= link_to "¿Quiénes Somos?",    help_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= javascript_include_tag "bootstrap" %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  This is the contact
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application. This was done by Alejandro Escobar, starting programmer.
</p>
<p>
	You can contact him at 
	<a href="mailto:alejoescobac@gmail.com">his email</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, '¿Quiénes Somos?') %>
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  </head>
  <body>
    <div class="row">
	<div class="span6" style="border-right: 2px solid #eaeaea">
		<h1 style="text-align:left">Misión</h1>	
		<p>Nuestra misión es contribuir a la formación integral de los estudiantes uniandinos ofreciendo espacios interdisciplinarios y flexibles, afianzando en ellos la conciencia de sus responsabilidades sociales y cívicas para que sean agentes de desarrollo y logren construir valor social en su entorno. </p>
	</div>	
	<div class="span5">
		<h1 style="text-align:left">Visión</h1>	
		<p>Para el año 2015 será el ente de referencia de Responsabilidad Social Universitaria a nivel nacional.</p>
	</div>
	</div>	
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	
<!--<img src="http://blogs.as.com/.a/6a00d83451bf7069e2017d42219079970c-450wi" style="float: right; margin-left: 30px; margin-bottom: 5px; position:relative; top:-45px">-->

<div id="myCarousel" class="carousel slide" style="float: right; margin-left: 30px; margin-bottom: 5px; position:relative; top:-45px">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><%=image_tag "rsu.jpg"%>
    	<div class="carousel-caption">
    		<h4 style="text-align:left">Primera Fundación</h4>
    		<p style="color:#ffffff; text-align:left">Descripción de la primera fundación.</p>
    	</div>	
    </div>		

    <div class="item"><%=image_tag "rsu1.jpg", style:"width:450px; height:300px"%>
    	<div class="carousel-caption">
    		<h4 style="text-align:left">Segunda Fundación</h4>
    		<p style="color:#ffffff; text-align:left">Descripción de la segunda fundación.</p>
    	</div>	
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev" style="top:50%">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next" style="top:50%">&rsaquo;</a>
</div>

  <h1 style = "font-size: 24pt; text-align: left">La ayuda Uniandina ha cambiado</h1>

  <h2 style = "text-align: left;">
    Participa en proyectos de responsabilidad social, encuentra el que más te gusta y participa.
  </h2>

  <%= link_to "¡Empieza ahora!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<div class="row">
	<div class="span4">
		<h2><%=image_tag "arrow.png", style:"width:30px; length:30px; position:relative; top:-5px; left:-20px"%> Descubre</h2>
		<p>Contamos con un gran número de fundaciones vinculadas, busca la que más se adapte a tus gustos.</p>
	</div>	
	<div class="span4">
		<h2><%=image_tag "arrow.png", style:"width:30px; length:30px; position:relative; top:-5px; left:-20px"%> Inscribete</h2>
		<p>Contactanos para iniciar tu proceso de participación</p>
	</div>	
	<div class="span4">
		<h2><%=image_tag "arrow.png", style:"width:30px; length:30px; position:relative; top:-5px; left:-20px"%> Participa</h2>
		<p>Inicia tu proceso de participación ahora, son muchas las cosas que tienes por aprender y aportar</p>
	</div>	
</div>

app/views/static_pages/organizaciones.html.erb
<div class="center hero-unit">
</div>	

app/views/static_pages/orgbank.html.erb
<% provide(:title, 'About Us') %>

<h1 style="text-align:left; border-bottom:2px solid #eaeaea">Banco de Organizaciones</h1>

<div class="center hero-unit" style="height:10px; border-style:solid">
	<%=image_tag "test.png", style: "width:100px; height:100px; position: absolute; left:520px; top:160px"%>
	<h3 style="position:absolute; left:700px; top:150px">Nombre de la Fundación</h3>
	<h4 style="position:absolute; left:700px; top:200px">Descripción de la fundación, propuesta de valor</h4>
</div>


app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>